dm1_registers.xml, riscv-debug-spec.tex
Also changed accesscs register to "progbufcs", since
it is specific to the program buffer control and status.
=> Remove last references to "Instruction Supply"

riscv-debug-spec.tex
Fix the compile errors introduced on #28
=> Finish up replacement of ibuf->progbuf

Makefile, abstract_commands.xml, dm1_registers.xml, dm2_registers.xml, registers.py, riscv-debug-spec.tex
This generates Chisel (Scala) code from the DMI Registers and Abstract Commands, which can be used in Chisel implementations of the Debug Module.
=> Generate chisel

core_registers.xml, hwbp_registers.xml, riscv-debug-spec.tex
I've used the python script to change all halt mode into debug mode. 
Po-wei
=> All halt mode changed to debug mode to synchronize with the priv spec.

xml/core_registers.xml, xml/sw_registers.tex
I haven't tested that this actually compiles, please test it before merging this PR. @palmer-dabbelt
=> Add missing SW Register File

introduction.tex
=> Fix language. We can only halt harts, not cores.

debugger_implementation.tex
=> Clarify/fix Quick Access example.

xml/dm_registers.xml
=> ABSTRACTCS: Correct inconsistency on the number of data words.

debug_module.tex, xml/dm_registers.xml
=> NDMRESET: Clarify what it may and may not do

xml/core_registers.xml
This allows single step with or without interrupts disabled.
=> Add stepie to dcsr.

xml/abstract_commands.xml
To remove the ambiguity about whether e.g.  reading a given CSR implies anything about other CSRs.
=> Clarify implications of CSR read, write, halt

xml/abstract_commands.xml
Clarify what happens on various Quick Access error situations
=> Quick Access error clarification

xml/core_registers.xml, xml/dm_registers.xml, xml/jtag_registers.xml
=> Add version constants for "not compatible".

.travis.yml
Making a pull request so Travis will build it. Not done yet.
=> Fix and speed up build.

xml/core_registers.xml
There was some confusion about this. See
https://groups.google.com/a/groups.riscv.org/forum/?utm_medium=email&utm_source=footer#!msg/debug/o9buamtml2s/a4r4qwBTFAAJ
=> Clarify dpc contents.

introduction.tex
=> Tighten up introduction lists.

debug_module.tex
=> Add table of Abstract Command Types

debug_module.tex, xml/dm_registers.xml
=> Configuration String -> Device Tree

debugger_implementation.tex
=> appendix: Use standard assembly format for sw

xml/dm_registers.xml
=> Clarify ndmreset.

xml/dm_registers.xml
=> Refuse unsupported bus accesses.

debugger_implementation.tex
=> Use a different word than "clobbered"

registers.py, xml/dm_registers.xml
The table still *just* fits on the page.
Issue #198
=> Explicitly list data[1-10] and progbuf[1-15]

README.md
=> Fix link to pre-built pdf

core_debug.tex, implementations.tex
=> Be more precise about processor vs hart

debugger_implementation.tex, future.tex, implementations.tex, introduction.tex, xml/hwbp_registers.xml
=> Be more precise about core vs hart

debug_module.tex, xml/dm_registers.xml
=> hawindowsel can be smaller, depends on # of harts

xml/dm_registers.xml
=> Clarify SBA unsupport access size error.

debug_module.tex
=> Explain that 1 in hart array mask means selected

xml/dm_registers.xml
=> Debuggers must not write sbcs while sbbusy is set

debug_module.tex
=> \Rcommand is not readable.

xml/abstract_commands.xml
This enables batch reading/writing of consecutively numbered registers.
Implements #250.
=> Add aarpostincrement to abstract register access.

xml/abstract_commands.xml
=> Side effects happen for abstract register accesses

riscv-debug-spec.tex, trigger.tex, xml/hwbp_registers.xml
This came out of today's debug call.
=> Solution to native triggers in M mode only systems

debug_module.tex
=> Be more clear about running signal.

xml/core_registers.xml
=> Don't change step/stepie while running.

xml/dm_registers.xml
=> Don't change selected harts during hart reset.

debug_module.tex
=> don't set most bits of DMCONTROL during abstract commands

xml/abstract_commands.xml
=> Clarify postexec when there is no Program Buffer

debug_module.tex
This should have been part of #330 but missed that boat.
=> Clarify lack of notification for other reset harts

implementations.tex
From a discussion on today's call.
=> Abstract commands might work on a hung hart.

xml/dm_registers.xml
=> Specify ackhavereset as W1.

xml/dm_registers.xml
=> Allow global reset to reset the DM.

riscv-debug-spec.tex, xml/hwbp_registers.xml
There was some e-mail discussion, subject:"ContextID trigger/trace"
=> Add ASID and context compare for triggers

debug_module.tex
In response to question in private e-mail.
=> Clarify what the 4 states are.

xml/dm_registers.xml
=> Reserve some DMI space for non-standard use.

xml/dm_registers.xml
=> \Fversion may be invalid when \Factive=0

xml/hwbp_registers.xml
=> Reserve trigger types for non-standard use.

xml/jtag_registers.xml
=> JTAG does not suggest any specific IDCODE encoding

xml/hwbp_registers.xml
=> Clarify that debuggers should honor maskmax.

xml/hwbp_registers.xml
Fix #452
Proposed changes to make the spec consistent on the access type of the tdata1 fields.
=> Change tdata1 access type

xml/hwbp_registers.xml
=> Clarify mcontrol.size.

.travis.yml, README.md, registers.py
Python 2 is on its way out, switch the script to Python 3 instead.
=> Update registers.py to use Python 3

xml/dm_registers.xml
=> Explicitly list cmderr=6 (reserved).

debug_module.tex, xml/dm_registers.xml
=> DM reset must also reset all the DM's harts.

debug_module.tex
=> Rewrite/clarify DM Reset Control

core_debug.tex
=> Document forward progress guarantees in Debug Mode.

core_debug.tex, implementations.tex, xml/core_registers.xml, xml/hwbp_registers.xml
Clarify what happens when those occur during single step. Hopefully
clarifies #510.
=> Use exception, trap, and interrupt as in ISA spec

debug_module.tex, debugger_implementation.tex, implementations.tex
=> Appendix B suggests signals for a DMI with one DTM connected to one DM

debug_module.tex
Also document a convention for trigger number by direction.
=> Explicitly allow uni-directional external triggers.

xml/abstract_commands.xml
=> Make explicit that aampostincrement is optional.

registers.py
Sorry to do this so piece-meal.
=> Remove end-of-line whitespace in generated comments.

xml/hwbp_registers.xml
My understanding is that this was the intention all along.
=> Follow suggestion in #544

implementations.tex
=> Update rocket-chip link in appendix to specific commit for permanence

xml/hwbp_registers.xml
See #555.
I have not tested this change by building a PDF (or anything else).
cc @ernie-sifive
=> Don't decrement icount.count when exception is blocked by tcontrol.mte

trigger.tex
For instance, there may be heterogeneous systems with some control processor harts that only support M mode and some full-featured harts that support more.
=> Triggers affect harts, not the system.

introduction.tex, overview.tex, riscv-debug-spec.tex, xml/core_registers.xml
=> RISC-V External Debug Support -> RISC-V Debug Support

core_debug.tex
Proposed solution to the mprven concerns.  Note that this is non-normative so there's no compatibility issue.
@allenjbaum @gfavor
=> Recommend mprven=1

xml/abstract_commands.xml
=> Change quick access exceptions to halt the target.

xml/hwbp_registers.xml
This helps some hardware implementations be simpler.  Addresses #550.
=> hit must be set on fire, may be set on match

xml/hwbp_registers.xml
but not generally useful. Addresses #572.
=> Chains should all have the same type.

xml/hwbp_registers.xml
=> Add clic bit to tmexttrigger.

trigger.tex
=> Breakpoint in trap handler *might* be unrecoverable.

riscv-debug-spec.tex, xml/hwbp_registers.xml
=> Clarify that ASID might come from satp or vsatp.

core_debug.tex, implementations.tex
=> Clarify details around fence and progbuf.

debug_module.tex, debugger_implementation.tex, dtm.tex, introduction.tex, jtagdtm.tex, overview.tex, xml/dm_registers.xml
Many acronymos contributed by Bruce Ableidinger.
=> Define some more terms/acronyms.

README.md
There is currently no latest draft. Fixes #626.
=> Remove latest draft link.

implementations.tex
Updates the description of the REQ_VALID and RSP_VALID DMI signals.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
=> Fix small grammatical error in suggested DMI signals

xml/core_registers.xml
Addresses https://lists.riscv.org/g/tech-debug/message/528
=> Clarify dcsr.cause=2

jtagdtm.tex
Change suggested by Robert Chyla.
=> Clarify unused debug connector pins names/uses.

riscv-debug-spec.tex, trigger.tex, xml/hwbp_registers.xml
=> Native triggers and reentrancy

.github/workflows/actions.yml
Hopefully fixes the automated build.
=> Run `apt update`

debugger_implementation.tex
=> SBA write memory example: configure size

xml/hwbp_registers.xml
=> Debuggers may set action!=1 when clearing dmode

xml/dm_registers.xml
Addresses email subject:"autoexecdata clarification"
=> autoexec* is the same as writing command

xml/dm_registers.xml
Address https://lists.riscv.org/g/tech-debug/topic/86745491
=> Clarify behavior of writes to abstractauto while busy=1

riscv-debug-spec.tex, xml/hwbp_registers.xml
=> Remove hcxe and scxe in tcontrol, using Smstateen instead.

xml/abstract_commands.xml
May be implemented, but not guaranteed to be useful.
=> Clarify partial abstract reg writes.

xml/dm_registers.xml
https://lists.riscv.org/g/tech-debug/topic/89540919#641
=> ackunavail doesn't clear unavail on harts that are still unavailable

xml/dm_registers.xml
https://lists.riscv.org/g/tech-debug/message/672
=> hawindow/hawindowsel are WARL

Sdtrig.tex, introduction.tex, xml/hwbp_registers.xml
Also clarify tdata2/tdata3 behavior when a trigger is disabled.
Add a paragraph about context restoring triggers.
=> Use trigger type 15 to indicate disabled.

README.md
Clarify the current version in readme.
=> Clarify the current version in readme.

implementations.tex
=> Clarify that PMP shouldn't prevent debug.

implementations.tex
=> Address #771

debugger_implementation.tex
=> Resumereq is W1 so cannot be cleared.

Sdtrig.tex
=> Clarify what fire and match mean for a trigger.

Sdext.tex
This ought to address @jrahmeh's concern.
=> Explicitly allow debug mode to access debug mode CSRs for #772.

debugger_implementation.tex
Tons of mailing list discussion, e.g. https://lists.riscv.org/g/tech-debug/message/1016
=> Suggest debugger behavior when icount stepping over restarting instruction

Sdtrig.tex, xml/hwbp_registers.xml
Now it's only in one place, instead of duplicated for mcontrol and mcontrol6.
=> Refactor AMO discussion.

xml/core_registers.xml
This is definitely what users want. Addresses #794.
=> stepie=0 should be supported.

Sdext.tex
This way I have a place to describe what happens with vector instructions.
Hopefully also answers part of #822.
=> Describe what happens on halt.

xml/jtag_registers.xml
=> Rename dtmc.dmihardreset field to dtmhardreset

Sdtrig.tex, xml/hwbp_registers.xml
Also be more consistent in using "TM external triggers" in definition of tmexttrigger.
Addresses #783
=> Clarify action 8/9 signal TM external triggers.

Sdtrig.tex, riscv-debug-spec.tex
See e-mail subject:"Sdtrig and CMO".
This partially contradicts what the CMO spec says, so we'll need to figure that out before merging this.
=> Describe how CMO instructions match triggers.

debug_module.tex, future.tex, introduction.tex, reading_order.tex, xml/dm_registers.xml
bus master -> bus coordinator
bus slave -> bus subordinate device
Addresses #844.
=> Don't say master/slave

xml/hwbp_registers.xml
=> Clarify when hit0/hit1 are updated by TM.

debugger_implementation.tex
=> Fix debugger examples: use transfer with write

debug_module.tex, introduction.tex, xml/abstract_commands.xml, xml/dm_registers.xml
These were first introduced in #728.
Hopefully I got everything.
=> AR: Remove Message Registers.

Sdext.tex
=> AR: Clarify section/chapter in Sdext.

Sdext.tex, xml/hwbp_registers.xml
=> AR: Clarify why icount matches on every trap.

xml/hwbp_registers.xml
=> AR: Clarify what tmexttrigger.intctl is for

Sdtrig.tex, xml/hwbp_registers.xml
=> Trigger CSRs provide access to underlying triggers.

Sdtrig.tex, xml/hwbp_registers.xml
See:
* https://lists.riscv.org/g/tech-debug/message/1407
* https://lists.riscv.org/g/tech-debug/files/meetings%202023/2023-01-10%20Debug%20Task%20Group%20Call%20Notes.pdf
* https://lists.riscv.org/g/tech-debug/files/meetings%202023/2023-01-10%20Debug%20Task%20Group%20Call%20Slides.pdf
=> Invalid addresses might not match.

registers.py
Looks OK.
Still missing:
* pretty register pictures
* macros for each register and field that automatically format consistently and link to the register/field definition
Usage: `registers.py --adoc <XML file>`
=> Add --adoc to registers.py.

build/Makefile
This PR fixes the asciidoc build that happens within the /build directory.
=> Fix asciidoc build within the build directory

debugger_implementation.adoc, dm_registers.adoc, riscv-debug-spec.adoc
=> Clean up remaining LaTeX register/field macros.

registers.py
The bit headers run into each other at maskmax of mcontrol. Is there a way I can specify left/right alignment in header columns?
=> Draw register diagrams using bytefield-svg

debug_module.adoc
=> Fix `hartset` -> {hartsel}

registers.py, xml/hwbp_registers.xml
=> Fix tdata1 having duplicate register diagrams

debugger_implementation.adoc, registers.py, xml/abstract_commands.xml
=> Minor fixes to table layout.

debug_module.adoc, debugger_implementation.adoc, dtm.adoc, introduction.adoc, registers.py, riscv-debug-header.adoc, xml/core_registers.xml, xml/dm_registers.xml, xml/jtag_registers.xml, xml/sw_registers.xml
Addresses all of #994 plus a few other ones.
=> Fix various issues with hyperlinks within the document.

xml/hwbp_registers.xml
=> Clarify timing support suggestion for a chain of mcontrol load triggers

introduction.adoc
Also sort the list of extensions alphabetically.
Follow up to #1062
=> Mention that the spec addresses Zicsr

Sdext.adoc
=> Clarify prv and v reflect privilege and virtualization modes.

debugger_implementation.adoc
=> Rewrite B.2.8 paragraph to be more clear.
