riscv/riscv-debug-spec

dm1_registers.xml
riscv-debug-spec.tex

I found the many uses of 'access' in the spec confusing. I renamed the bus-related registers and fields to "sb..." and renamed the register "access" to "accesscs" since that seemed to be the pattern for "control and status" registers.
I fixed a couple typos as well.

Unalias 'access' registers and fields for clarity

---

dm1_registers.xml
riscv-debug-spec.tex

Even if some dislike the implications of the name, we should be consistent and clear in the spec. And it's easier to find-and-replace if we choose a different name.

system_bus: be consistent and always call it 'System Bus'

---

abstract_commands.xml
riscv-debug-spec.tex

I was confused about arg0 and arg1. Clarifying.

Clarify "arguments" to commands

---

dm1_registers.xml

Why is Program Buffer only allowed to be size 8?
In our previous implementation, for an XLEN=32 design, we only needed 7 words to implement the desired functionality for both program buffer and data transfer. With the latest "quick access" proposal we'll need 3 words for data. Is it possible to do what we need with only 4 words? (or 5 if we must implement ebreak at the end)?

Allow size 4 for the program buffer

---

dm1_registers.xml

Size of program buffer was bumped to 12 words, but we left the limited size in the text.
I think rather than saying what the legal sizes are, we should just say what you get with each size (e.g. 4 words allows quick access to registers, 8 to memory, 10 to CSRs). I just made those numbers up though.

Make comments on program buffer size match the address map.

---

jtag_registers.xml
riscv-debug-spec.tex

I did a pass over the JTAG DTM Section. I clarified some things that I think weren't clear, and renamed DBUS to DMI to be consistent with the rest of the doc.

jtag_dtm: Clarifications, DBUS->DMI

---

jtag_registers.xml
riscv-debug-spec.tex

-IR width of 5 is only a minimum
-Remove commentary about \idle.
This is my followup to your comments on  #19

jtag: More clarifications

---

dm1_registers.xml

One of the error cases (SB read underflow) seemed incorrectly described. Also added some formatting fixes.

SystemBus: Clean up some formatting and error specification notes.

---

dm1_registers.xml

This addresses #23 , and also cleans up the naming of all Control and Status registers to be the same.

Use consistent 'Control and Status' naming for CS registers.

---

riscv-debug-spec.tex

This addresses the question from me on the mailing list and in today's meeting. There were a few similar questions, so it seems worthwhile to make things more explicit.

Clarify that the halt state of all harts is maintained through reset

---

abstract_commands.xml
dm1_registers.xml

This seems important for an implementation to be able to decide what abstract command you're talking about... if you have another encoding in mind, let me know.

Add explicit type field to Abstract Command.

---

dm2_registers.xml
riscv-debug-spec.tex

Adjust serial addresses to be more sensically aligned and to use up a more isolated section of the memory space.

serial: tweak addresses

---

xml/dm_registers.xml

Many registers were labeled W0 even though their description stated otherwise. Make them consistent.
Closes #85 along with similar issues found on the way.

Correct a bunch of W0 registers

---

xml/abstract_commands.xml
xml/core_registers.xml

Addresses #66,  #75. Also clarifies that DPC behaves like MEPC and friends -- it gets the address of the PC which entered debug mode (not the last instruction which has already completed).

DPC: Clarifications on its meaning/usage

---

xml/core_registers.xml

2 bits isn't really enough for a version field.
Changed the "current version" from 1 to 4 so that existing
implementations aren't affected by this change.
Fixes issue #86.

Increase xdebugver field size to 4 bits.

---

implementations.tex

This updates the "Hardware implementations" to be a bit more concrete about the actual current implementations, rocket-chip and riscv-isa-sim. Happy to add others as well.

implementations: be a bit more concrete about the example 

---

core_debug.tex

Although from the SW debugger perspective it is not necessary to define dret, we should still reserve the opcode. DRET is needed for some instruction feeding approaches, and also defning it here will alow the same debug module hardware to be used to debug different core implementations.

Define DRET instruction

---

debug_module.tex

Since anynonexistent is not referenced earlier, clarify that it it is in dmstatus.
Addresses #65

Forward reference for anynonexistent

---

overview.tex

It's not really spontaneous, as the first part of the sentence says, it's because trigger conditions were met.
Addresses #64

remove "spontaneous"

---

dtm.tex
jtagdtm.tex
riscv-debug-spec.tex

as it is really part of the specification.

jtagdtm: Move it out of the appendix

---

xml/core_registers.xml

There was still some references to "halt mode" vs. "debug Mode". The causes in DCSR.cause should specify "why was debug mode entered", not really "why did hart halt".

clarify DCSR.cause

---

xml/abstract_commands.xml

By adding this clarification, it removes a race/ambiguity about the meaning of error halt/resume for Access Register command

Clarify when you would get error halt/resume

---

registers.py

See https://github.com/riscv/riscv-openocd/pull/81

Use LL instead of L for 64-bit constant suffix.

---

debug_module.tex
xml/dm_registers.xml
xml/jtag_registers.xml

Closes #116 
There really is no reason to have DMI return error responses, as in all other error cases a sticky error status bit is set. The only one left here was for System Bus access. This PR removes this last remaining case.

DMI does not have an Error response

---

xml/hwbp_registers.xml

addresses #52 
At this point we need to remove this from the spec, or agree on it and deprecate the trigger type if it turns out this was defined all wrong.

icount: remove warning

---

xml/dm_registers.xml

Since more than one hart can be halted at a  time, correct this statement.

Correct plurality of halted harts in haltsum

---

registers.py

Make fails on systems with python3 interpreter linked to python

Python interpreter to be used should default to Python2

---

xml/core_registers.xml

This will help avoid a trap where an implementation might end up with
prv 0 when entering debug out of reset. Even in that case prv should be
set from the privilege mode of the processor, which should be machine
mode, but specifying this as the actual value makes things a little
simpler.

Change dcsr.prv reset value to 3

---

xml/dm_registers.xml

to be BWC and not overlap with ABSTRACTAUTO.
Fixes typo introduced in #218

haltsum1: correct its address 

---

preamble.tex
registers.py

Previously it was confusing that especially Table 3.8 would end up in
the dmstatus Section. #300

Force the register-address table in place.

---

riscv-debug-spec.tex
xml/hwbp_registers.xml

This resolves problems when matching against instructions that aren't
MXLEN bits wide, and allows matches against data accesses of specific
sizes.

Add size to mcontrol.

---

xml/abstract_commands.xml

Define cmderr for non-existent register access.

---

debug_module.tex

Based on feedback by Allen that resetting just one hart in a multi-hart
core can be complex/poorly defined, depending on implementation.

Allow extra harts to be reset.

---

xml/dm_registers.xml

Fixes #319.
Also explain why there are separate bits in the first place, and make
them both W1.

clrresethaltreq trumps setresethaltreq

---

core_debug.tex

This is an alternate proposal to #329, which fixing #314 in a different
way.

Allow control xfers in progbuf to act as illegal.

---

core_debug.tex
debug_module.tex
debugger_implementation.tex
dtm.tex
future.tex
implementations.tex
introduction.tex
overview.tex
xml/dm_registers.xml

Note, the e.g. must be followed by a backslash to tell LaTeX that it
isn't the end of a sentence.
$0x400$ tells LaTeX to read "0 x 400" as math, not what you want

m "LaTeX/english issues: eg. -> e.g., etc"

---

xml/abstract_commands.xml
xml/dm_registers.xml

Explicitly state which arguments abstract commands do or do not change.

Language, formatting, and abstract cmd arguments.

---

xml/jtag_registers.xml

Now it's consistent with dtmcs.dmistat.
This reverts 7f0f09a0. It is no longer true that a debugger can assume
dmi.data contains a valid value unless a read was explicitly executed,
so there's no sense in accommodating that case.

Reset dmi.op to 0 instead of 2.

---

introduction.tex
xml/dm_registers.xml
xml/jtag_registers.xml

The definition used to be vague. I think this is the one that makes the
most sense, and shouldn't cause any problems. (Possibly we don't want
this for ackhavereset. I sent e-mail about that.)
The bits that are defined as W1 are:
DM: ackhavreset, setresethaltreq, clrresethaltreq
JTAG: dmihardreset, dmireset

Clarify W1.

---

xml/abstract_commands.xml

This resolves a contradiction in the spec.
Fixes #365.

Abstract reg access is independent of run/halt.

---

dtm.tex
introduction.tex
jtagdtm.tex

For inches, apparently the thing to do is spell them out, so I did that.

Format quotes correctly.

---

debug_module.tex
debugger_implementation.tex
xml/dm_registers.xml

They already mostly were, but then I clarified some stuff and broke
keeping haltreq high during reset, which is the only mechanism to catch
a hart out of reset if optional reselthaltreq isn't implemented.
Also:
* resume ack is cleared by the DM when resumereq is written 1.
* haltreq can be high together with hartreset.
This is the minimal version of #378. It has all the same functionality,
but lacks some of #378's clarifications, which may be making this harder
to review.

Make haltreq and resumereq proper write-only.

---

README.md

Update the link to spec PDF, to reflect change of filename. To address Issue #386.

Fix link to PDF

---

debug_module.tex
introduction.tex
xml/core_registers.xml
xml/dm_registers.xml

This allows a group of harts to simultaneously halt when any of them
hits a breakpoint, or even when some other event occurs in the system.

Add halt groups and external triggers.

---

xml/hwbp_registers.xml

Add nmi bit to etrigger.

---

xml/hwbp_registers.xml

Fixes #415.
This change is compatible because the new behavior is optional.

Address triggers may fire on any accessed address.

---

debug_module.tex

Fixes #413.
This is a pretty important clarification. Is it an erratum?

Clarify that harts halt out of reset if haltreq=1

---

debug_module.tex

This change already went into master. This PR is to add the same text into release as a bugfix.
I don't believe the release version mentions anywhere that haltreq applies coming out of reset. It used to be in there, and is still the intention. There was some e-mail discussion about this: subject:"Halt on reset"

Clarify that harts halt out of reset if haltreq=1 (#419)

---

xml/abstract_commands.xml

Abstract memory accesses use the low bits of arg0.

---

trigger.tex
xml/hwbp_registers.xml

See #422. This might break software that's not ready for the
possibility, but I believe the privilege spec is already clear that the
Debug CSRs are optional.

All trigger registers are optional

---

debug_module.tex
xml/dm_registers.xml

Also make some more required guarantees about future versions.
Unfortunately there are a number of side effects to reading the version,
but none of them are a big deal.

Explain how to detect the version.

---

Makefile
longtable.sty

This bug was reported (with a fix) way back in 2003 (7 years before
RISC-V was started at Berkeley) at
https://www.latex-project.org/cgi-bin/ltxbugs2html.new?pr=tools/3512
For us, it should fix #432. I'll apply this to the release branch once
it merges to master.

Don't run text off a page when longtable is used.

---

jtagdtm.tex

See #436. Does this change need to go in 0.13 as well?

When extending IR, BYPASS still is all ones.

---

xml/hwbp_registers.xml

Recommend that we attempt to match every address that is accessed.
This extends the recommendation of just doing that on equality matches to all matches, although it's just a recommendation so still optional.

Tweak address matches.

---

xml/dm_registers.xml

The definition of sberror says:
> While this field is non-zero, no more system bus accesses can be initiated by the Debug Module.
and sbbusyerror says:
> While this field is set, no more system bus accesses can be initiated by the Debug Module.
This means that either one being non-zero prevents further access.  Section 3.14.24 shouldn't say that no access takes place only if **both** are non-zero.

sberror and sbbusyerror don't both have to be non-zero to prevent access

---

riscv-debug-spec.tex

This is the same fundamental change for the same observed problem as the base ISA spec pull request 370: https://github.com/riscv/riscv-isa-manual/pull/370
> Adobe Acrobat Reader DC 19.010.20099 for Windows doesn't work well with the ligatures found in the RISC-V specs. Searching for words like "defined" doesn't work due to the "fi" ligature. Copying "defined" to the clipboard will drop the "fi" and only copy "dened" (or there's possibly an unprintable character there).
> 
> Other PDF viewers seem to have better behavior than the Adobe product (which is odd since Adobe invented PDF). However, enough people use Acrobat that it ought to be supported if possible.
> 
> I found a fix for this situation on:
> https://superuser.com/questions/165073/is-it-possible-to-remove-ligatures-from-copied-t …

Finesse ligatures to work with Adobe Acrobat Reader search and cut-and-paste

---

xml/hwbp_registers.xml

The *external* debugger must restore tselect.

---

Makefile
core_debug.tex
debug_module.tex
debugger_implementation.tex
implementations.tex
registers.py
riscv-debug-spec.tex
trigger.tex
xml/abstract_commands.xml
xml/core_registers.xml
xml/dm_registers.xml
xml/hwbp_registers.xml
xml/jtag_registers.xml
xml/serial.xml
xml/sw_registers.xml

This solves the problem we have with the same field existing in multiple
registers, as reported in #451.

Fully qualify register/field macro names.

---

xml/hwbp_registers.xml

Without S-mode, textra.svalue and .sselect should be 0

---

core_debug.tex
xml/core_registers.xml
xml/hwbp_registers.xml

See https://lists.riscv.org/g/tech-debug/message/756

Addressing more feedback from Marc Gauthier.

---

introduction.tex

This change might break debuggers that are written to support 0.13.
OpenOCD and Lauterbach have stated they're fine with that, and there
probably aren't that many other debuggers out there. The fix will be
trivial.

Change R/W1C to reduce requirements on hardware.

---

xml/hwbp_registers.xml

It really should be in the S-mode section of CSRs, but that would be an
incompatible change. Fixes #410.

Mention the scontext reg number isn't conventional

---

trigger.tex
xml/hwbp_registers.xml

This contains a bunch of improvements that came out of an e-mail
discussion. The biggest one is that it specifies the priority of various
triggers compared to the exceptions already in the Privileged Spec.

Tighten up trigger specification.

---

.gitignore

Add a gitignore file to keep the output of `git status` a bit cleaner. There's still the checked-in PDF that differs all the time, but that needs to be solved by CI or another way which doesn't include checking in this file.

Git ignore intermediate and output files

---

debug_module.tex

These were showing up as ??? in the output document.

Fix page references in cmdtype table

---

riscv-debug-spec.tex

Email addresses are typically given like "<email@example.com>" with no
spaces. That was the case for Tim's email address, but not for the other
one. Fix that for consistency (it's the title page after all!)

Tiny style fix for email "link" on title page

---

jtagdtm.tex
xml/jtag_registers.xml

Fix  broken references to tables in the JTAG DTM part of the spec.

Fix wrong table reference

---

registers.py

Previously they were emitted in `Chisel._` (compatability mode). As part of upgrading to `chisel3`, export them as `chisel3` (note this doesn't actually need to change anything) else in the emitted code.

Make the emitted registers chisel3

---

debug_module.tex
xml/dm_registers.xml

This addresses a concern of how the debugger can know when hardware is
ready to be debugged, discussed on the mailing list. subject:"Email
discussion: how can a debugger know when a target is ready for it?"

Time may pass before dmactive becomes high.

---

core_debug.tex

This mirrors a change made in the privileged spec:
https://github.com/riscv/riscv-isa-manual/commit/569d07195a8495460f04592d8455153f730a0f54

Clear MPRV when resuming into lower privilege mode.

---

debug_module.tex

It's not necessary to have this requirement, since there are other
mechanisms to ensure harts halt out of reset if that's what the debugger
wants.
Fixes #357.

Halt state may not be preserved across reset.

---

xml/dm_registers.xml

This is not forwards compatible. Debuggers that rely on haltsum0 would
break with this change. But it makes the debug interface on tiny 1-hart
systems smaller, especially because it allows the number of address bits
in the DMI to be 1 less. (Haltsum0 at 0x40 due to other efforts to
maintain backwards compatibility.)
Fixes #389.

Make haltsum0 optional if there is only one hart.

---

debug_module.tex
xml/dm_registers.xml

Mostly inspired by e-mail discussion with Subject:"resume groups in
addition to halt groups".

Add resume groups.

---

xml/dm_registers.xml

Autoincrement only happens if an access actually takes place.
On the list, see subject:"sbaccess ambiguity".

Fix conflict in sbdata0/sbautoincrement definition.

---

trigger.tex
xml/hwbp_registers.xml

Otherwise you might end up in a situation where regular software can
control when to enter debug mode.

Clarify action=1 (enter Debug Mode) with dmode=0

---

xml/hwbp_registers.xml

This is important, because there is literally no space in the register
for the field when XLEN is 32.
Problem reported by Allen Baum.

sizehi only exists if Xlen>64.

---

xml/core_registers.xml

If a privilege mode is not supported by the core, or if a privilege
change is not allowed, the dcsr.prv register is set to a supported
value. This makes this register WARL, not R/W, as indicated in the
table.

dcsr.prv should be WARL, not R/W

---

xml/dm_registers.xml

I'm of the view that there are sufficient changes in 0.14 to warrant a distinct encoding for the version. This pull request simply adds that encoding to the spec.

Adding version encoding for 0.14 spec.

---

core_debug.tex
xml/dm_registers.xml

New dmcontrol.relaxedpriv bit as discussed in https://lists.riscv.org/g/tech-debug/topic/75549024

Add abstractcs.relaxedpriv

---

xml/abstract_commands.xml

Adding brief clarification of permitted "aamvirtual" bit behavior on systems without address translation, per the following discussion: https://lists.riscv.org/g/tech-debug/topic/72759746

aamvirtual: Clarification for systems without address translations

---

xml/hwbp_registers.xml

When doing mcontrol6 work, I noticed that icount and etrigger have references to fields in mcontrol rather than to fields in themselves.  I'm making this a separate PR since these changes are really unrelated to mcontrol6.

Fix links to point to fields in the correct registers.

---

core_debug.tex
implementations.tex
preamble.tex

Changed the dret section in the normative architecture section to only include architectural requirements and refer to the appendix for implementation details.
Added UNSPECIFIED to the preamble to conform to the overall architecture.

Add dret to rule 8.

---

implementations.tex

A question came up about the relationship between PMP and debug in an Execution-Based design.  This PR adds a clarifying statement to the non-normative appendix section describing Execution-Based implementations saying that for debug to be possible, the PMP must allow access to the debug module address range when in debug mode.

Clarify that PMP must allow access to DM for debug to be possible

---

debug_module.tex

I had a conversation today with someone who was confused by "clobber" so I propose to use the official term.

Use official RISC-V terminology

---

xml/dm_registers.xml

This proposed spec change would allow a DM time to deactivate gracefully by requiring a debugger to poll after writing 0 to dmcontrol.dmactive.  Currently the spec only states that a debugger should poll after writing 1 to this bit.
Prior discussion can be found in my post to the tech-debug mailing list on 2020.10.13, Subject "How to reliably inform debugger of completion of DM inactivation?".

require polling of dmactive low as well as dmactive high transitions

---

debug_module.tex

This was rendering as "??" in the PDF.  Now it points to the hartinfo register.

Fix broken reference

---

debug_module.tex

Most references are "implicit ebreak" but there is one instance of "implied ebreak".  Make all of them "implicit".

Use consistent term when referring to impebreak

---

debug_module.tex
xml/dm_registers.xml

Make unavail sticky, needing to be acknowledged with new ackunavail bit.
This is a backwards incompatible change. I think it's OK because
implementations that support unavailable harts are rare (I don't know of
any), and the change only means that debuggers must be updated. If
hardware doesn't implement this then everything will still work,
although users might not be notified when harts become unavailable.
Fixes #461.

Debuggers should know when harts are unavailable.

---

registers.py
xml/dm_registers.xml

But don't give them each a description if it's redundant.
The main change here is that registers.py now generates an "index" table
that can be split across pages.
This change supersedes #560.

List all DM registers in Table 3.8.

---

xml/hwbp_registers.xml

See mailing list. Subject:"On icount triggers"

Add pending state/bit to icount.

---

registers.py

We used to not do this because those fields would often have the same
name as some other field, and there was a name collision. Now however we
have long, fully qualified names. This change is needed for #588 which
references \FcsrTextraSixtyfourSselect.

Create LaTeX macros for fields without descriptions.

---

xml/hwbp_registers.xml

sbytemask field in textra32 and textra64 provides byte-granular comparison of the svalue trigger value to the scontext CSR

Added sbytemask field to textra32 and textra64

---

riscv-debug-spec.tex
xml/dm_registers.xml

Addresses #519. Went with the simple version without reading the keepalive values.

Add keepalive feature.

---

xml/hwbp_registers.xml

Also some formatting cleanup to make things more consistent.
Addresses #570.

AMO operations may be ignored by mcontrol triggers.

---

debug_module.tex
xml/dm_registers.xml

Currently there is a well-defined way for a debugger to determine when reset has begun and completed for any arbitrary subset of harts (most recently discussed in PR 480, 494).  However the system as a whole is composed of more than just the harts, and there is no overarching “havendmreset” signal analogous to the per-hart “havereset” signals to indicate when this state outside of the harts has completed reset.  
Because some system state accessible to a debugger (for example, peripherals' register space via SBA) can continue to be in reset after all harts in a system have completed reset,  it is useful for the debugger to know when ndmreset is still happening and when it has completed.
This PR implements a way for a debugger to determine if ndmreset has completed on implementations that …

add dmstatus.ndmresetpending to allow a debugger to determine when ndmreset is complete

---

trigger.tex

Addresses #573.
This new requirement only changes hardware with writable types. Even
there it is trivial to implement as long as types 2 or 6 are supported,
and those types become selected when 0 is written.

Explain how to simply write any trigger.

---

xml/jtag_registers.xml

I noticed that dtmcs.version did not have a value specified to indicate spec version 1.0.

Add version 1.0 value to dtmcs.version field

---

introduction.tex

I was informed that the reference to the Privileged Spec is outdated and received a suggestion to change it to point to a version that includes hypervisor.

Update version of priv spec to one with hypervisor

---

core_debug.tex
trigger.tex
xml/core_registers.xml
xml/hwbp_registers.xml

This is also what the privileged spec does.

Use A-mode instead of "A mode" consistently.

---

core_debug.tex
implementations.tex

Suggested by Ken Dockser, since dret has no meaning outside specific
implementations.

Move dret completely into the appendix.

---

xml/hwbp_registers.xml

In a pipelined core, executing an instruction takes multiple cycles. It is also possible for an instruction to be executed but not committed or executed out-of-order with respect to the preceding/succeeding instruction.  The 'timing' bit description as written appears to exclude pipelining, speculation, and out-of-order execution.
Changed 'executed' to 'committed' three times each in 'timing' description of MCONTROL and MCONTROL6 registers.

Clarify MCONTROL/MCONTROL6 'timing' description

---

core_debug.tex
debug_module.tex
dtm.tex
introduction.tex
trigger.tex

There are separate definition-of-done requirements for ISA vs. non-ISA
specs. Our spec contains both, so clearly mark what is what.

Divide the spec into ISA and non-ISA.

---

debug_module.tex

This fixes a contradiction pointed out in #619, in favor of the language
in dmcs2.

hasel etc. are only ignored by abstract commands.

---

xml/dm_registers.xml

Fixes the first issue brought up in #619.
Also remove some duplicate language.

Unselected harts may change groups when hgwrite=1

---

debug_module.tex

As discussed in the meeting this morning, there's no value in constraining this and different implementations do different things.

Clarify what happens to halted harts upon DM reset

---

xml/abstract_commands.xml

When transfer=0 but postincrement=1, it is undefined whether regno is
incremented or not.
See mailing list discussion subject:"aarpostincrement and transfer=0"

Clarify postincrement/transfer behavior.

---

README.md

The debug task group mailing list has been moved to lists.riscv.org.
This updates the link for better discoverability.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

Update link to mailing list in README.md

---

registers.py

Read-only CSRs cause an exception when you write to them. What we mean
is that there are no writable bits, so writes are simply ignored.
Fixes #645

Don't call read/write CSRs read-only.

---

xml/core_registers.xml

action=1 enters debug mode, not action=0.

Fix obvious error in dcsr.cause=2 description.

---

debug_module.tex
xml/dm_registers.xml

With input from Oded Yishay.
This is not technically backwards compatible, but if I recall the meeting discussion correctly SiFive already implements it this way, and everybody agreed it makes more sense.

Resume ack is set for any resume cause.

---

xml/hwbp_registers.xml

Fixes #690.
This doesn't conform with what @timsifive said but I think it's correct.  I also tried to clearly discourage use of this and explain why.
@valtrix
@JamesKenneyImperas

Specify accessibility of mscontext

---

Sdext.tex
riscv-debug-spec.tex
xml/core_registers.xml

I was going to say that it should stop the time CSR plus any custom CSRs that the custom extension might want to stop.  But custom extensions can always define their behavior to depend on standard CSR bits like stoptime so I decided that this wouldn't add anything.

Stoptime clarification per architecture review

---

debug_module.tex
xml/dm_registers.xml

The macro simply makes a reference for the index, but does not display
the internal text.

Fix uses of \index macro.

---

xml/hwbp_registers.xml

The privileged spec says that medeleg only delegates synchronous exceptions so clarify that in the case of tmexttrigger medeleg is delegating an asynchronous exception.
Also clarify what happens to tmexttrigger events that happen while the trigger is prevented from firing.

Clarify tmexttrigger with action=0.

---

introduction.tex
xml/hwbp_registers.xml

Per mailing list discussion subject:"etrigger.nmi".

Move nmi from etrigger to itrigger.

---

xml/hwbp_registers.xml

This value does not end up in the actual document, but it should be
right in the source anyway.

Fix reset value of etrigger.type

---

xml/hwbp_registers.xml

If masking is supported then tdata2 must be able to hold all XLEN bits.

---

debug_module.tex
xml/dm_registers.xml

Also describe where this structure is mentioned in the priv spec.

constrptr points to the configuration structure, not string.

---

xml/hwbp_registers.xml

As discussed in the TG meeting.

Clarify behavior of low bits of tdata2 when match=1.

---

xml/hwbp_registers.xml

mscontext is accessible in S mode.
tselect is WARL.  This was in the XML but not in the final PDF.

Clarifications/bug fixes: mscontext and tselect

---

debug_module.tex

It is not necessary to first select and then issue the command in
dmcontrol. The old language could have been interpreted that way.

Select and issue a command can be simultaneous

---

Sdtrig.tex
introduction.tex
xml/hwbp_registers.xml

Specifically, now icount triggers on M-Mode only systems are more
useful, because the count might not decrement while in an interrupt
handler.
See 2022 email discussion subject:"trigger questions"

Tighten up language around icount matching.

---

debugger_implementation.tex

To make that fit in a reasonable section, combine the separate
external/native debug implementation chapters into a single debugger
implementation chapter.

Describe debug_defines.h.

---

debug_module.tex
introduction.tex
xml/dm_registers.xml

Message Registers allow data to be sent to the other side, but not to be
read back by the side that wrote the data.
This allows smaller FPGA implementations by duplicating the storage and
removing muxes in the design, addressing part of #717.
It is incompatible with old debuggers, if they use these registers in
surprising ways.

Make data registers Message Registers.

---

introduction.tex
xml/dm_registers.xml

This allows a more efficient implementation, especially on FPGAs.
See #717.

The program buffer may not be readable.

---

registers.py
xml/abstract_commands.xml
xml/core_registers.xml
xml/dm_registers.xml
xml/hwbp_registers.xml
xml/jtag_registers.xml

Generate constants in the C header for the values. E.g.
```
#define CSR_TDATA1_TYPE_NONE                0
#define CSR_TDATA1_TYPE_LEGACY              1
#define CSR_TDATA1_TYPE_MCONTROL            2
#define CSR_TDATA1_TYPE_ICOUNT              3
...
```
Make formatting slightly more consistent in the PDF.

Add field values to XML register description.

---

registers.py
xml/hwbp_registers.xml

Leave the descriptions empty, and change registers.py to not emit
anything for values whose descriptions are empty.
I'm not a huge fan of the duplication of those values in the XML file,
but I don't want to invent a new mechanism to avoid it right now. (Ooh,
we could use M4 to generate the XML and use an existing mechanism...)

Add trigger action values, for debug_defines.h.

---

Sdtrig.tex

Those values are fixed, and there's no need to send somebody looking for
a different document just to see the very short description.

List trigger actions described by the trace spec

---

.github/workflows/publish.yml
.github/workflows/verify.yml

In this PR, I prototype a flow to automatically rebuild pdf and releasing CI, and use git tag to release new version of debug spec, which was discussed in 2022-05-10 Debug Task Group Call. Ask @timsifive for review.
Here is the new release strategy: For pdfs which need to be rebuilt: tag it with `v{version}-{stable|release|draft}`, for example `v0.13-release`, CI will automatically rebuild and send it to GitHub release page.
There current status of debug spec is: `v0.13` is released, `v1.0` is stable or draft(I'm not so sure about this), but not released yet. we need to have at least two tags: `v0.13-release` and `v1.0-stable` for the releasing procedure.
For the `v0.13-release`, we need to backport(rebase) this PR to 0.13(currently 4e0bb0fc2d843473db2356623792c6b7603b94d4 and …

Add GitHub Action to auto release.

---

debugger_implementation.tex

It says:
> In Update-DR the operation will start, and in Capture-DR its results will be captured into data.
So I think that more time might be necessary between Update-DR and Capture-DR rather than the other order.  (Arguably, it's between those states regardless of the order in which they're listed but specifying them in temporal order is less confusing.)

Fix order of TAP states to be consistent.

---

debug_module.tex

Specifically, it wasn't true for abstractauto.

Remove clarifying information that is false.

---

Sdtrig.tex

**Clarify/Simplify the sentence:**
- Since the tdata registers are WARL, hardware should clear the action
field whenever the action field is 1, dmode is cleared, and the new
value of the action field would also be 1.
**Change into:**
- If dmode is 0, writing 1 to the action clears the action field.
Reference: https://github.com/riscv/riscv-debug-spec/issues/746

Clarify writing 1 to action on dmode=0

---

xml/jtag_registers.xml

It's not clear, as reported in #760.

Clarify dmi.{data,address} behavior.

---

xml/dm_registers.xml

Changed the wording in the description of "abstractcs.relaxedpriv" because the original wording was unclear and could have been mis-interpreted:
Changes made:
- full permissions --> full permission checks
- relaxed permissions --> relaxed permission checks

abstractcs.relaxedpriv: Clarify the description

---

xml/hwbp_registers.xml

Previously the spec could be interpreted to mean that dmode is ignored for trigger type 15. Fix this ambiguity and, for consistency, make it so dmode is active for trigger type 15.

Dmode is still active for trigger type 15.

---

xml/core_registers.xml

More accurate state the behavior specified in Section 4.1, so people don't have to read that in order to really understand this part.
See #766.

Clarify stoptime behavior.

---

debug_module.tex

Clarify this by explicitly saying the behavior only applies to running/halted harts respectively.

halt/resume groups don't apply to unavailable harts.

---

Sdtrig.tex

Move some text out of an explanation block. It's awkward to start a Section with one, and also the text doesn't make sense without reading the explanation.

Improve Native Triggers formatting.

---

implementations.tex

Say that you have an icount trigger enabled but icount.pending=0 and you have an execute trigger on the instruction pointed to by dpc.  You leave debug mode.  This will hit the execute trigger (which is higher priority than icount since pending=0) and immediately enter debug mode again.  What happens with icount.pending?
If this reentry to debug mode is considered a trap from some regular mode to debug mode then icount.pending would be set even though you didn't execute an instruction and you didn't take a "trap" as defined in the privileged spec.  That leads to a forward-progress problem because you didn't advance pc to the next instruction, a branch/jump target, or a trap handler (as defined in the priv spec).  There would also be no trap in a more abstract implementation where …

Clarify the term "trap" in execution-based implementations.

---

introduction.tex
xml/hwbp_registers.xml

This lets an implementation be more specific about when a trigger fired in relation to the instruction that matched, to avoid user confusion when triggers fire late.
It also simplifies the spec around desired trigger timing behavior, simply asking for best effort to match the recommendation from the table.

Expand mcontrol6.hit into hit0 and hit1, and remove mcontrol6.timing.

---

introduction.tex
jtagdtm.tex

Make it more clear that MIPI-10 should be sufficient for everyone, mostly by clearly putting MIPI-20 into an alternate connector section.
Expand just a tiny bit on cJTAG.
Update MIPI references to the current version of that document, and mention the pinouts using the same names used there.

Clarify JTAG connector section.

---

xml/hwbp_registers.xml

Previously we said "completes" which is not well defined. Also be clear that xRET instructions count.

Clarify icount decrements on instruction execution

---

debug_module.tex

Harts/triggers belong to exactly one halt/resume group.

---

introduction.tex
xml/hwbp_registers.xml

Lots of email discussion, subject:"removed mcontrol6.timing,
compatibility"
Now that hit0/hit1 clearly describe when a trigger hit, we don't need a
separate mechanism to communicate whether triggers hit before/after. The
only remaining benefit timing provided was that it would let the
debugger know when the trigger is set what the timing behavior would
probably be. (Emphasis on probably, since it's not possible to honor the
requested timing in all situations.)

Remove timing bit again. Introduce tinfo.version.

---

Sdext.tex
Sdtrig.tex
introduction.tex

The privileged spec already requires this.
This addresses a mailing list discussion subject:Clarification of enumeration procedure in Sdtrig ISA extension

Clarify: non-existent CSR access raises an exception.

---

xml/hwbp_registers.xml

Uncertain trigger matches occur when the hardware can't do a precise comparison, e.g. on batched vector accesses, and far AMO data.
This lets the user select whether they want the trigger to fire if a match is uncertain, and the hardware can indicate whether a given match was certain or not.
Lots of mailing list discussion prompted this:
https://lists.riscv.org/g/tech-debug/topic/94864865#1030

Add mcontrol6.{uncertain,uncertainen} bits.

---

Sdtrig.tex

See e-mail discussion subject:"Size for address trigger matching and vector"

Document trigger behavior with vector/push/pop accesses.

---

xml/jtag_registers.xml

Maybe would have avoided #819.

Clarify that dmi.op describe dmi.address contents.

---

debug_module.tex
xml/core_registers.xml

Addresses https://github.com/riscv/riscv-debug-spec/issues/824.

Document behavior for abstract dpc access while running.

---

xml/hwbp_registers.xml

"Inhibited" is not well-defined, and this language is no longer necessary. It was added when the original sentence said:
> When \FcsrIcountCount is greater than 1, every instruction completed or
> trap taken from a mode where the trigger is enabled decrements
> \FcsrIcountCount by 1.
Now there is no more reference to a mode, so the clarification isn't needed either.
Addresses #813

icount: Remove confusing statement about inhibited trigger.

---

xml/hwbp_registers.xml

Those two are distinct in the case of icount, where pending becomes set on match, and firing happens later. We want to make sure not to fire in a place where match is disallowed.
Addresses #812.

textra inhibits firing in addition to matching.

---

debugger_implementation.tex
xml/core_registers.xml

Fixes #827.  Also changed trigger examples to fix some bugs, add the type field, add vs/vu in some examples, enhance one example to include textra, etc.

Remove references to the timing bit.

---

debugger_implementation.tex

Now include both mechanisms suggested for native triggers in single-privilege-mode systems, instead of just carefully counting instruction.
Addresses #830.
---
Improve single step description for different debug features
This commit updates the description of single step implementation in the debugger_implementation.tex file. It now provides a more detailed and clear explanation on how to single step through code running in the same privilege mode as the debugger, depending on the availability of \FcsrTcontrolMpte, \FcsrTcontrolMte, and automatically preventing \FcsrMcontrolSixAction=0 triggers from matching when entering a trap handler.
(gpt-4)

Document native single step options.

---

Sdtrig.tex

This is a substantive change, but a bugfix, so OK to merge.
Addresses #812.

Reentrant trigger prevention inhibits match *or fire*

---

xml/hwbp_registers.xml

The rationale is that if icount is enabled in the current mode and the mode of the trap handler, when you single step you don't want to step past the first instruction of the trap handler, which you didn't know was going to be executed. Having to step multiple times to get past an interrupt to actually execute the instruction you tended to step is addressed the same way as already documented in the appendix.
Addresses a question from #842.

Clarify that icount decrements on interrupt traps.

---

Sdext.tex

Because the definition of DPC already says "Executing the Program Buffer may cause the value of dpc to become unspecified."
This fixes a contradiction in the spec.

D-Mode exceptions may modify DPC

---

Sdext.tex

Allow partial register updates for instructions that already do that.
Based on lots of mailing list discussion:
https://lists.riscv.org/g/tech-debug/topic/98622044#1178

Clarify trap in progbuf behavior.

---

debug_module.tex

This fixes a bug introduced in #506.
See e-mail: https://lists.riscv.org/g/tech-debug/topic/99398782#1291

External trigger signals inputs don't cause trigger output.

---

Sdext.tex

The existing language implied that hit bits would be updated, which doesn't make any sense. That's because that line was written before we had hit bits.
Clarifies #851.

In Debug Mode, triggers don't match or fire.

---

implementations.tex

Fix typo in execution appendix: execute -> postexec

---

debug_module.tex
future.tex
introduction.tex
xml/dm_registers.xml
xml/jtag_registers.xml

Address AR feedback:
> Master/slave terminology is obviously being replaced across RV specs -
> in a somewhat haphazard manner as far as what is being used for
> replacements.  The ARC suggests using the following (and will be
> proposing this to be the standard replacement across RV specs):
> Manager/subordinate  (which remains intuitive and happens to maintain
> the M/S starting letters fwiw)

AR: Use manager/subordinate for master/slave.

---

debug_module.tex

- Clarified that both the concerned requirements apply only to the case of progbufsize==1, as discussed in
https://github.com/riscv/riscv-debug-spec/issues/863
- Minor reword and simplification of the sentences
- Changed the order of paragraphs so that:
- Generic requirements are stated first (Debug Mode, cmderr, ...)
- Special requirements for progbufsize==1 are mentioned later

Program Buffer: Clarify requirements for case progbufsize==1

---

Sdext.tex
Sdtrig.tex
debug_module.tex
introduction.tex
xml/jtag_registers.xml

We can always be more clear using other terminology.

AR: Don't use "non-existent" in reference to register.

---

debug_module.tex
xml/abstract_commands.xml
xml/dm_registers.xml

aampostincrement implies the implementation does not use simple MRs.

AR: Clarify message register uses.

---

Sdtrig.tex

Based on discussion in #870, where Paul mentioned:
> I don't think that it's incompatible. Old implementations would have
> said that they do the debug spec but there was no "Sdtrig" until
> recently. I guess that somebody in the last year or so could have
> claimed Sdtrig compliance without any triggers but that seems unlikely
> and I don't think that adding this new requirement would require them to
> change anything other than some Powerpoint slides.

Sdtrig must implement at least one trigger.

---

implementations.tex

The performance of this code doesn't matter (compared to how slow JTAG is), and the fewer side effects debugging has, the better.

Recommend debug ROM is not cached.

---

Sdtrig.tex

After a very long e-mail discussion, we landed on maintaining
unimplemented CSR behavior as-is. Just add a quick note to be explicit
about that intention. The end of the discussion is basically:
1. If Sdtrig CSRs are accessed when they are not implemented or Sdtrig
is not implemented, the hart will trap. This is to maintain backwards
compatibility with existing implementations that use this for
discovery.
2. If Sdext CSRs are accessed when they are not implemented, the hart
will trap. (No need to specify behavior when Sdext is not
implemented, because in that case Debug Mode doesn't exist and the
CSRs aren't accessible anyway.) This is to be consistent with Sdtrig
behavior.

AR: Comment on unimplemented CSR behavior.

---

Sdtrig.tex

From Greg: "... why is this non-normative comment even necessary?  It's directly consistent with 1.12, and it's compatible with 1.13 which allows for trapping and just doesn't require it.  In other words, wrt 1.13, this trapping mandate by Debug 1.0 doesn't conflict with Priv 1.13.  And that allows Debug 1.0 to come along and tighten what is allowed by 1.13."

AR: Remove comment about privspec/CSR behavior

---

introduction.tex

I added a hint as to how they were considered as LaTeX comments, because I want to keep that info but don't want to word it nicely/completely enough to actually have it as part of the spec text.

AR: List which extensions were considered.

---

xml/core_registers.xml

See https://lists.riscv.org/g/tech-debug/message/1387

dscratch[01] are DXLEN bits wide.

---

Sdext.tex

If Sdext is implemented and Sdtrig is not implemented, then accessing any of the Sdtrig CSRs must raise an illegal instruction exception.
(This is already said in privspec 1.12, but that might change in the future.)

AR: Clarify unimplemented Sdtrig.

---

xml/hwbp_registers.xml

It was a bit confusing before. Hopefully now it's more clear how they relate, and why you might want each one.

AR: Clarify mcontext/hcontext.

---

introduction.tex
xml/hwbp_registers.xml

Reverts #723, which would result in mepc etc. being clobbered if a breakpoint trigger would fire in the most privileged mode.
Specifically, consider:
1. icount is set so that it'll trigger on the first instruction of an exception handler.
2. Code takes an exception, saving mepc etc.
3. Now icount fires causing a breakpoint exception, clobbering mepc.

AR: tcontrol.mie applies to all traps, not just breakpoints

---

Sdtrig.tex
xml/hwbp_registers.xml

Incorporate more feedback from AR. Moved this into a separate Sdtrig section, since the discussion could also apply to instructions that cause triggers beside memory access ones. (E.g. an instruction that combines memory accesses with a trigger, and itrigger.)
Follow up to #883.

AR: Clarify triggers and multiple state changes

---

Sdtrig.tex

Addresses #892.
Here's the privspec table:
And here is what ours looks like:

AR: Update priority table from latest privspec

---

xml/hwbp_registers.xml

itrigger numbers relate to the value written to *cause when the trap is taken.
Addresses #889.

AR: Clarify itrigger and trigger number translation

---

xml/hwbp_registers.xml

Addresses #905, which reports that in 1.13 higher exception codes will be used.

AR: Comment etrigger limited to 32 exceptions if XLEN=32

---

xml/hwbp_registers.xml

AR: Comment itrigger limited to 32 ints if XLEN=32

---

registers.py

1) We need to add ULL modifier to all values to fix some issues with `set_field` and `get_field` OpenOCD macros (for example, when `mask` = 2 << 31, it leads to UB)

Fix macro generation

---

debug_reg_printer.c

`riscv_debug_reg_fields_to_s()` exited early without processing the last field.

The last field of a register was not printed

---

debug_reg_printer.c
debug_reg_printer.h
registers.py

Don't mention fields whose value is 0.
New format:
{sbautoincrement=1 sbaccess=64bit sbreadonaddr=1 }

Make register dump output more concise.

---

xml/hwbp_registers.xml

Don't make this contingent on hit0/hit1 being changed, since those bits are optional. (Although I discourage anyone from not implementing hit0/hit1.)
Addresses #915.

uncertain is updated when trigger fires.

---

Sdtrig.tex
introduction.tex
xml/hwbp_registers.xml

Refer to "trigger registers" as "Trigger Module Registers"

---

xml/hwbp_registers.xml

Make it clear that on reset, the triggers are also reset. The defined values already ensure that triggers are disabled when they have their reset values.
Last change for #913.

CSR reset values apply to underlying triggers.

---

.github/workflows/verify.yml
build/Makefile
jtagdtm.adoc
registers.py

Only used for JTAG registers right now since they're missing from adoc altogether. This is mostly a proof of concept of the workflow. There is definitely some formatting issues with the generated adoc, which should be trivial to adjust once I know what correct adoc looks like.

Call registers.py during build to convert XML to adoc.

---

build/Makefile
registers.py
riscv-debug-header.adoc
xml/abstract_commands.xml
xml/core_registers.xml
xml/dm_registers.xml
xml/hwbp_registers.xml
xml/jtag_registers.xml
xml/sw_registers.xml

Create def.adoc files that define a macro for each register and field. Use those macros from all the XML files.
If this looks right, I can do the same search/replace in all the remaining adoc files.

Convert many LaTeX register/field macros to asciidoc

---

registers.py

Without this, the first line of what should be the actual file contents ended up as part of the comment.

Add newline to end of "Auto-generated ..."

---

registers.py
xml/abstract_commands.xml
xml/core_registers.xml
xml/dm_registers.xml
xml/hwbp_registers.xml

And some minor other improvements.

Replace LaTeX {steps} inside XML files.

---

registers.py
xml/hwbp_registers.xml

This enables us to override the auto-generated diagram when it doesn't do a good job.
Hopefully we won't need it much. If we do, the auto-generation code probably needs improvement.

Add <diagram> option to <register> entries.

---

introduction.adoc
registers.py
riscv-debug-header.adoc

The only text change is on the title page. My name is now first, and I removed email addresses because they just don't work with whatever `:authors:` does.

Misc asciidoc fixes.

---

xml/abstract_commands.xml
xml/hwbp_registers.xml

Remove stray $ left over from LaTeX.

---

registers.py

Without this, the `[cols=...]` line would show up in the rendered text (at the start of section 4.10).

Ensure a newline at the end of registers description

---

Sdext.adoc

Section 4.1 already says "Effective XLEN is DXLEN." The statement about communicating XLEN to the user is unnecessary to the spec, and unclear, so we don't need it.

Remove Section 4.9: XLEN

---

debug_module.adoc

Definition of `dmstatus.ndmresetpending` bit says that this bit should be equal to 1 while `dmcontrol.ndmreset` is asserted, implying that `dmstatus.ndmresetpending` is readable even under ndmreset.
Therefore, this merge request updates the text that specifies which DM register accesses are defined under ndmreset.
The change has been discussed here: https://github.com/riscv/riscv-debug-spec/issues/944

Fix contradictory req. for ndmresetpending

---

introduction.adoc
xml/hwbp_registers.xml

Still todo, is figure out what to call XLEN there. In the introduction we mention what XLEN means for Debug and M-Mode, but some of these registers are accessible in other modes also.

Make the data of the *context registers 32 bits wide.

---

Sdtrig.adoc

Load data before trigger priority was ambiguous.

---

debug_module.adoc

There is a paragraph in section 3.3 that explains how to determined HARTSELLEN. However, the word "hartsel" has been left out, and the sentence no longer makes sense. The fix is for adding "hartsel" back.

fixed missing hartsel reference when determining HARTSELLEN

---

Sdtrig.adoc

Autowidth led to the first column to be so narrow that "Value" was taking up two rows.

Fix Action encoding table column width.

---

debug_module.adoc

In section 3.13 (Version Detection) the `dmactive` bit was wrongly assigned to `dmstatus` register. Also, the debug module version  should be from `dmstatus.version` rather than `tinfo.version`

dmactive is part of dmcontrol, and debug module version is from dmstatus

---

Sdtrig.adoc

These got deleted by the asciidoc conversion.
Fixes #1015.

"Native Triggers": Add in mepc/mcause back in.

---

debug_module.adoc

Seems like these references were lost durining convertion from LaTeX. See https://github.com/riscv/riscv-debug-spec/blob/f510a7dd33317d0eee0f26b4fa082cd43a5ac7ea/debug_module.tex#L125-L126

Restore references to `mhartid` in `debug_module.adoc`

---

xml/core_registers.xml

2 changes:
1. Add extcause field, which gives is room for a double trap cause plus a few others in case of future need.
2. Add cetrig bit to let a debugger control behavior when a double trap occurs.
We expect this to be approved together with #988, but I want to keep them separate so we can easily have one approved/merged without the other.

Add support for Smdbltrp.

---

Sdtrig.adoc

`(TM)`  seems to show as a trademark in asciidoc (at least in the github renderer). Escaping the opening parenthesis `\(TM)` appears to fix that.

Don't trademark the trigger module

---

debug_module.adoc

Seems like these references were lost durining convertion from LaTeX. See https://github.com/riscv/riscv-debug-spec/blob/f510a7dd33317d0eee0f26b4fa082cd43a5ac7ea/debug_module.tex#L405-L406

Restore references to `command.cmdtype` and `tab:cmdtype` table

---

debug_module.adoc

Seems like these references were lost durining convertion from LaTeX.
See https://github.com/riscv/riscv-debug-spec/blob/f510a7dd33317d0eee0f26b4fa082cd43a5ac7ea/debug_module.tex#L442

Restore reference to `dmstatus.impebreak`

---

debug_module.adoc

Seems like these references were lost durining convertion from LaTeX.
See https://github.com/riscv/riscv-debug-spec/blob/f510a7dd33317d0eee0f26b4fa082cd43a5ac7ea/debug_module.tex#L468

Restore references to `pc` in [3.8. Program Buffer]

---

xml/dm_registers.xml

Names of registers not defined in this specification are highlighted using backticks throughout the specification.
`mconfigptr` used to be an exception.

Fix formatting for `mconfigptr`

---

xml/dm_registers.xml

LaTeX refernces didn't use numbers and replaced them with text.
Seems like this caused an error during convertion and references to `sbcs.sbaccess64/128` started to refer to `sbcs.sbaccess` field with an addition of `Sixtyfour` and `OneTwentyeight` respectively.

Fix references to `sbcs.sbaccess64/128`

---

Sdext.adoc

Seems like these references were lost durining convertion from LaTeX.
See https://github.com/riscv/riscv-debug-spec/blob/f510a7dd33317d0eee0f26b4fa082cd43a5ac7ea/Sdext.tex#L47-L49

Restore reference to `time`

---

Sdext.adoc

Without the additional formatting the
> but count must be able to count
part seems a bit strange.

Replace "count" with a reference to 'icount.count'

---

Sdtrig.adoc

It is covered by
> Whether data store triggers match on AMOs is UNSPECIFIED.

Eliminate redundant statement about AMO's stored value availability

---

Sdtrig.adoc

Instead of describing a recommended implementation (which didn't cover all cases), explicitly state the value that is illegal and let hardware choose how to do that.
Addresses #995.

Simplify WARL description for dmode=0 and action=1.

---

xml/hwbp_registers.xml

Previously, the first write of match=1 might fail because the value in tdata2 is incompatible.
Addresses #1014

Update maskmax6 detection algorithm to always work

---

debug_module.adoc

The check was introduced in #324.
AFAIU, after #361 and #383 were merged made the check became obsolete.
IMHO, the check is confusing and redundant, since all the fields in question are `W1`/`WARZ`, so it can be dropped.

Drop `dmcontrol` check before abstract command

---

xml/jtag_registers.xml

The confusion was raised in the 2024-07-08 meeting.

Clarify that DMI nop does not affect busy/error.

---

debug_module.adoc
xml/dm_registers.xml

This makes things work better in case the debugger wants to reset but doesn't know hartsel, as mentioned in #1021.
Also the debugger should write dmactive=0 to perform a reset, instead of "may".

DM should ignore some bits while abstract command is executing

---

implementations.adoc

`sw 0x400(zero), <gpr>` has incorrect assembly syntax, source register should come first.

Fix `sw` instruction assembly in Appendix A.2

---

xml/abstract_commands.xml

I'm not sure if this is necessary. Does RISC-V allow data loads to differ from instruction fetches? For a long time any mention of caches was avoided in all specs.
Inspired by #1062.

Clarify Memory Access acts like data access.

---

debugger_implementation.adoc

Clarify why to use progbuf to access FPRs/CSRs

---

Sdtrig.adoc

Addresses https://github.com/riscv-non-isa/riscv-trace-spec/issues/115

Triggers with action != 0 or 1 fire independently.

---

implementations.adoc

I don't know if we can just agree that this is inconsequential and merge it, if we should merge it and create another release candidate, or if we should just delay dealing with this PR until after ratification.
Fixes #1096.

Fix asciidoc conversion missing word for #1096.

---

README.md

The Readme still contained old (pre-adoc) build instructions. Fix it.
Mention also the use of submodules which are needed for the documentation to build.

Readme: Fix build instructions

---

xml/jtag_registers.xml

I was contacted by someone who was confused about this situation:
- kick off a DMI operation (e.g. read)
- read DTMCS while the DMI operation is still in progress
The question was whether this should set busy or not.  My understanding is that "an operation was attempted while a DMI request is still in progress" means that a new _DMI operation_ was attempted, not a _JTAG operation_ to read DTMCS.

Clarify that "an operation" is a DMI operation.

---

introduction.adoc

The link got broken during LaTeX to AsciiDoc conversion. Link: https://github.com/riscv/riscv-debug-spec/blob/f510a7dd33317d0eee0f26b4fa082cd43a5ac7ea/introduction.tex#L172

Fix the link to `dmstatus.version` in "Minor Changes from 0.13 to 1.0"
